/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vote;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import login.AfterLoginUI;
import report.ReportUI;
import login.LoginInformation;

/**
 *
 * @author moise
 */
public class VoteGUI extends javax.swing.JFrame {
    //Voter array list
    private ArrayList<Vote> voter;
    private LoginInformation l;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoteGUI.class.getName());

    /**
     * Creates new form VoteGUI
     */
    public VoteGUI(LoginInformation l) {
        initComponents();
        voter = new ArrayList<>();
        timelineLbl.setVisible(true);
        timelineTF.setVisible(true);
        countyLbl.setVisible(true);
        countyTF.setVisible(true);
        populationLbl.setVisible(true);
        populationTF.setVisible(true);
        namesLbl.setVisible(false);
        namesTF.setVisible(false);
        idLbl.setVisible(false);
        idTF.setVisible(false);
        voteLbl.setVisible(false);
        voteTF.setVisible(false);
        reasonLbl.setVisible(false);
        reasonTF.setVisible(false);
        infrastructureLbl.setVisible(false);
        infrastructureTF.setVisible(false);
        businessLbl.setVisible(false);
        businessTF.setVisible(false);
        suggestionLbl.setVisible(false);
        suggestionTF.setVisible(false);
        this.l=l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        typeGrp = new javax.swing.ButtonGroup();
        timelineLbl = new javax.swing.JLabel();
        countyLbl = new javax.swing.JLabel();
        populationLbl = new javax.swing.JLabel();
        namesLbl = new javax.swing.JLabel();
        addVoterBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        voteLbl = new javax.swing.JLabel();
        reasonLbl = new javax.swing.JLabel();
        infrastructureTF = new javax.swing.JTextField();
        timelineTF = new javax.swing.JTextField();
        countyTF = new javax.swing.JTextField();
        populationTF = new javax.swing.JTextField();
        namesTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        voteTF = new javax.swing.JTextField();
        reasonTF = new javax.swing.JTextField();
        infrastructureRB = new javax.swing.JRadioButton();
        businessRB = new javax.swing.JRadioButton();
        clearBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        infrastructureLbl = new javax.swing.JLabel();
        businessTF = new javax.swing.JTextField();
        businessLbl = new javax.swing.JLabel();
        suggestionLbl = new javax.swing.JLabel();
        suggestionTF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        voterRB = new javax.swing.JRadioButton();
        orgDetailsBtn = new javax.swing.JButton();
        outputLbl = new javax.swing.JLabel();
        reportBtn = new javax.swing.JButton();
        mentorBtn = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        timelineLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        timelineLbl.setText("Timeline");

        countyLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        countyLbl.setText("County");

        populationLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        populationLbl.setText("Population");

        namesLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        namesLbl.setText("Voter Name");

        addVoterBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addVoterBtn.setText("Add Voter");
        addVoterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoterBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        titleLbl.setText("Vote Application");

        idLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        idLbl.setText("Voter Id");

        voteLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        voteLbl.setText("Vote");

        reasonLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        reasonLbl.setText("Reason");

        countyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countyTFActionPerformed(evt);
            }
        });

        namesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesTFActionPerformed(evt);
            }
        });

        typeGrp.add(infrastructureRB);
        infrastructureRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        infrastructureRB.setText("Infrastructure");
        infrastructureRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infrastructureRBActionPerformed(evt);
            }
        });

        typeGrp.add(businessRB);
        businessRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        businessRB.setText("BusinessAid");
        businessRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessRBActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        infrastructureLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        infrastructureLbl.setText("Infrastructure");

        businessLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        businessLbl.setText("BusinessAid");

        suggestionLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        suggestionLbl.setText("Suggestion");

        saveBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        saveBtn.setText("Save");

        searchBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        searchBtn.setText("Search");

        deleteBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        deleteBtn.setText("Delete");

        typeGrp.add(voterRB);
        voterRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        voterRB.setText("Voter");

        orgDetailsBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        orgDetailsBtn.setText("Details of Vote");
        orgDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgDetailsBtnActionPerformed(evt);
            }
        });

        reportBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        reportBtn.setText("Report App");
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        mentorBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        mentorBtn.setText("MentorApp");
        mentorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentorBtnActionPerformed(evt);
            }
        });

        mainBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        mainBtn.setText("MainPage");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLbl)
                            .addComponent(namesLbl)
                            .addComponent(populationLbl)
                            .addComponent(countyLbl)
                            .addComponent(timelineLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infrastructureLbl)
                            .addComponent(businessLbl)
                            .addComponent(suggestionLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(voteLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reasonLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(populationTF)
                                    .addComponent(namesTF))
                                .addGap(21, 21, 21)
                                .addComponent(outputLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(timelineTF, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .addComponent(countyTF))
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(reasonTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .addComponent(voteTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(infrastructureTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(businessTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(suggestionTF, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(mainBtn)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(businessRB)
                            .addComponent(infrastructureRB)
                            .addComponent(addVoterBtn)
                            .addComponent(voterRB)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(orgDetailsBtn)
                            .addComponent(clearBtn))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reportBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mentorBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(voterRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infrastructureRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(businessRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addVoterBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(namesLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(titleLbl)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(outputLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timelineLbl)
                                    .addComponent(timelineTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(countyLbl)
                                    .addComponent(countyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(populationLbl)
                                    .addComponent(populationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(namesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idLbl)
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(voteLbl)
                                    .addComponent(voteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(displayBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orgDetailsBtn)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mentorBtn)
                            .addComponent(reportBtn)
                            .addComponent(mainBtn))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reasonLbl)
                            .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infrastructureLbl)
                            .addComponent(infrastructureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(businessLbl)
                            .addComponent(businessTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suggestionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suggestionLbl))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Add voters to arraylist
    private void addVoterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoterBtnActionPerformed
        // TODO add your handling code here:
        if (voterRB.isSelected()) {
            String voterId = idTF.getText();
            String voterNames = namesTF.getText();
            String vote = voteTF.getText();
            String reason = reasonTF.getText();
            Vote v = new Vote(voterNames, voterId, vote, reason);
            voter.add(v);
        }
        if (infrastructureRB.isSelected()) {
            String infrastructure = infrastructureTF.getText();
            String voterId = idTF.getText();
            String voterNames = namesTF.getText();
            String vote = voteTF.getText();
            String reason = reasonTF.getText();
            //Vote v =new Vote(infrastructure,timeline, county, population, totalVotes, yesVotes, noVotes, spoiledVotes,voterId,voterNames,vote, reason);
            InfrastructureVote i = new InfrastructureVote(infrastructure, voterId, voterNames, vote, reason);
            voter.add(i);

        }
        if (businessRB.isSelected()) {
            String aidType = businessTF.getText();
            String voterId = idTF.getText();
            String voterNames = namesTF.getText();
            String vote = voteTF.getText();
            String reason = reasonTF.getText();
            //Vote v =new Vote(infrastructure,timeline, county, population, totalVotes, yesVotes, noVotes, spoiledVotes,voterId,voterNames,vote, reason);
            BusinessAidVote b = new BusinessAidVote(aidType, voterId, voterNames, vote, reason);
            voter.add(b);
        }
    }//GEN-LAST:event_addVoterBtnActionPerformed

    private void namesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namesTFActionPerformed

    private void countyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countyTFActionPerformed
    //display voters and organiser details 
    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        if (voter.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no voters to display");
        } else {
            for (int i = 0; i < voter.size(); i++) {
                Vote v = voter.get(i);
                JOptionPane.showMessageDialog(this, v.voteDetails());
            }
        }
    }//GEN-LAST:event_displayBtnActionPerformed
    //Clear text fields
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed

        timelineTF.setText(" ");
        countyTF.setText(" ");
        populationTF.setText(" ");
        namesTF.setText(" ");
        idTF.setText(" ");
        voteTF.setText(" ");
        reasonTF.setText(" ");
        infrastructureTF.setText(" ");
        businessTF.setText(" ");
        suggestionTF.setText(" ");


    }//GEN-LAST:event_clearBtnActionPerformed
    //To do an infrastructure vote
    private void infrastructureRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infrastructureRBActionPerformed
        // TODO add your handling code here:
        timelineLbl.setVisible(true);
        timelineTF.setVisible(true);
        countyLbl.setVisible(true);
        countyTF.setVisible(true);
        populationLbl.setVisible(true);
        populationTF.setVisible(true);
        namesLbl.setVisible(true);
        namesTF.setVisible(true);
        idLbl.setVisible(true);
        idTF.setVisible(true);
        voteLbl.setVisible(true);
        voteTF.setVisible(true);
        reasonLbl.setVisible(true);
        reasonTF.setVisible(true);
        infrastructureLbl.setVisible(true);
        infrastructureTF.setVisible(true);
        businessLbl.setVisible(false);
        businessTF.setVisible(false);
        suggestionLbl.setVisible(false);
        suggestionTF.setVisible(false);

    }//GEN-LAST:event_infrastructureRBActionPerformed
    //To do a business and aid vote
    private void businessRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessRBActionPerformed
        // TODO add your handling code here:
        timelineLbl.setVisible(true);
        timelineTF.setVisible(true);
        countyLbl.setVisible(true);
        countyTF.setVisible(true);
        populationLbl.setVisible(true);
        populationTF.setVisible(true);
        namesLbl.setVisible(true);
        namesTF.setVisible(true);
        idLbl.setVisible(true);
        idTF.setVisible(true);
        voteLbl.setVisible(true);
        voteTF.setVisible(true);
        reasonLbl.setVisible(true);
        reasonTF.setVisible(true);
        infrastructureLbl.setVisible(false);
        infrastructureTF.setVisible(false);
        businessLbl.setVisible(true);
        businessTF.setVisible(true);
        suggestionLbl.setVisible(false);
        suggestionTF.setVisible(false);
    }//GEN-LAST:event_businessRBActionPerformed
    //button to get details of vote details as well as the details of the votes result
    private void orgDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgDetailsBtnActionPerformed
        // TODO add your handling code here:
        String timeline=timelineTF.getText();
        String county=countyTF.getText();
        int population=Integer.parseInt(populationTF.getText());
        Organiser o = new Organiser(timeline,county,population);
        JOptionPane.showMessageDialog(this, o.printDetails());
    }//GEN-LAST:event_orgDetailsBtnActionPerformed
    //button to go to report app app

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        new ReportUI(l).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reportBtnActionPerformed
    //button to go to mentor app
    private void mentorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentorBtnActionPerformed
        // TODO add your handling code here:
        new ContactMentorGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mentorBtnActionPerformed
    //Go to mainpage
    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        new AfterLoginUI(l).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VoteGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVoterBtn;
    private javax.swing.JLabel businessLbl;
    private javax.swing.JRadioButton businessRB;
    private javax.swing.JTextField businessTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel countyLbl;
    private javax.swing.JTextField countyTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel infrastructureLbl;
    private javax.swing.JRadioButton infrastructureRB;
    private javax.swing.JTextField infrastructureTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton mainBtn;
    private javax.swing.JButton mentorBtn;
    private javax.swing.JLabel namesLbl;
    private javax.swing.JTextField namesTF;
    private javax.swing.JButton orgDetailsBtn;
    private javax.swing.JLabel outputLbl;
    private javax.swing.JLabel populationLbl;
    private javax.swing.JTextField populationTF;
    private javax.swing.JLabel reasonLbl;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel suggestionLbl;
    private javax.swing.JTextField suggestionTF;
    private javax.swing.JLabel timelineLbl;
    private javax.swing.JTextField timelineTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup typeGrp;
    private javax.swing.JLabel voteLbl;
    private javax.swing.JTextField voteTF;
    private javax.swing.JRadioButton voterRB;
    // End of variables declaration//GEN-END:variables
}
