/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ABC
 */
public class LoginUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginUI.class.getName());

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#dd7a3f"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldForID = new javax.swing.JTextField();
        jPasswordFieldForPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButtonForSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Log-In");

        jLabel2.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        jTextFieldForID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForIDActionPerformed(evt);
            }
        });

        jPasswordFieldForPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldForPasswordActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(243, 225, 210));
        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 3, 36)); // NOI18N
        jButton1.setText("Sign-In");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonForSignUp.setBackground(new java.awt.Color(243, 225, 210));
        jButtonForSignUp.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 3, 36)); // NOI18N
        jButtonForSignUp.setText("Sign-Up");
        jButtonForSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldForID, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldForPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonForSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldForID))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldForPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonForSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldForIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForIDActionPerformed

    private void jPasswordFieldForPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldForPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldForPasswordActionPerformed

    private void jButtonForSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForSignUpActionPerformed
        // TODO add your handling code here:
        SignUpUI signUpDialog = new SignUpUI(this, true);   // argument 'this' means current class.
        // argument 'true' means users won't be able to use other pages except "SignUpUI"
        signUpDialog.setVisible(true);


    }//GEN-LAST:event_jButtonForSignUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jTextFieldForID.getText();
        String password = String.valueOf(jPasswordFieldForPassword.getPassword());

        String validFirstName, validLastName, validEMail, validID, validSex, validPhoneNumber, validAddress, validAge;
        validFirstName = validLastName = validEMail = validID = validSex = validPhoneNumber = validAddress = validAge = null;

        boolean idValidation = false;
        boolean passwordValidation = false;

        // declare objects
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            // create objects
            inFile = new File("users", "users.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            // use objects
            String line = br.readLine();
            while (line != null) {
                String[] parts = line.split(", ");

                if (id.equals(parts[3])) // check the id
                {
                    if (password.equals(parts[4])) // check the password
                    {
                        // if both id and password are correct
                        idValidation = true;
                        passwordValidation = true;

                        validFirstName = parts[0];
                        validLastName = parts[1];
                        validEMail = parts[2];
                        validID = parts[3];
                        validSex = parts[5];
                        validPhoneNumber = parts[6];
                        validAddress = parts[7];
                        validAge = parts[8];
                        break;
                    } else // if id is correct, but password is incorrect
                    {
                        idValidation = true;
                        break;
                    }
                }

                line = br.readLine(); // go to the next line
            }

            if (idValidation == true && passwordValidation == true) // if user id and password are correct
            {
                JOptionPane.showMessageDialog(null, "Log-In completed!");

                LoginInformation information = new LoginInformation(validFirstName, validLastName, validEMail, validID, validSex, validPhoneNumber, validAddress, validAge);

                AfterLoginUI LoginUI = new AfterLoginUI(information);

                LoginUI.setVisible(true);   // open the AfterLoginUI
                dispose();  // exit
            } else if (idValidation == true && passwordValidation == false) {
                JOptionPane.showMessageDialog(null, "Wrong Password");
            } else {
                JOptionPane.showMessageDialog(null, "Wrong ID");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonForSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldForPassword;
    private javax.swing.JTextField jTextFieldForID;
    // End of variables declaration//GEN-END:variables
}
