/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mentor;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import login.AfterLoginUI;
import report.ReportUI;
import vote.VoteGUI;
import login.LoginInformation;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author marti
 */
public class ContactMentorGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactMentorGUI.class.getName());
    private LoginInformation l;
    private ArrayList<Business> businessList;
    //display message which we will add different variables depending on field
    private String displayMessage;

    /**
     * Creates new form ContactMentorGUI
     */
    public ContactMentorGUI(LoginInformation l) {
        this.l = l;
        initComponents();
        this.getContentPane().setBackground(Color.decode("#dd7a3f"));
        //declare array list
        businessList = new ArrayList<>();
        //this is to make all the dif types of business text fields disappear once the page loads and then when they click a RB it will make them appear
        ownerLbl.setVisible(false);
        ownerTf.setVisible(false);
        owner1Lbl.setVisible(false);
        owner1Tf.setVisible(false);
        owner2Lbl.setVisible(false);
        owner2Tf.setVisible(false);
        ceoLbl.setVisible(false);
        ceoTf.setVisible(false);
        numOfBoardMembersLbl.setVisible(false);
        numOfBoardMembersTf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiobutton = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        infoLbl1 = new javax.swing.JLabel();
        infoLbl2 = new javax.swing.JLabel();
        businessNameLbl = new javax.swing.JLabel();
        businessTypeLbl = new javax.swing.JLabel();
        industryLbl = new javax.swing.JLabel();
        numOfStaffLbl = new javax.swing.JLabel();
        shortGoalsLbl = new javax.swing.JLabel();
        longGoalsLbl = new javax.swing.JLabel();
        businessNameTf = new javax.swing.JTextField();
        industryTf = new javax.swing.JTextField();
        numOfStaffTf = new javax.swing.JTextField();
        shortGoalsTf = new javax.swing.JTextField();
        longGoalsTf = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();
        voteBtn = new javax.swing.JButton();
        reportBtn = new javax.swing.JButton();
        soletraderRB = new javax.swing.JRadioButton();
        partnershipRB = new javax.swing.JRadioButton();
        limitedRB = new javax.swing.JRadioButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        ownerLbl = new javax.swing.JLabel();
        ownerTf = new javax.swing.JTextField();
        owner1Lbl = new javax.swing.JLabel();
        owner2Lbl = new javax.swing.JLabel();
        owner1Tf = new javax.swing.JTextField();
        owner2Tf = new javax.swing.JTextField();
        ceoLbl = new javax.swing.JLabel();
        ceoTf = new javax.swing.JTextField();
        numOfBoardMembersLbl = new javax.swing.JLabel();
        numOfBoardMembersTf = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("INNOVATION");

        infoLbl1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 20)); // NOI18N
        infoLbl1.setForeground(new java.awt.Color(255, 255, 255));
        infoLbl1.setText("Need help with your business?");

        infoLbl2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 16)); // NOI18N
        infoLbl2.setForeground(new java.awt.Color(255, 255, 255));
        infoLbl2.setText("Submit your business below and one of our mentors will assist you!");

        businessNameLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 16)); // NOI18N
        businessNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        businessNameLbl.setText("Business Name:");

        businessTypeLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 16)); // NOI18N
        businessTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        businessTypeLbl.setText("Business Type:");

        industryLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 16)); // NOI18N
        industryLbl.setForeground(new java.awt.Color(255, 255, 255));
        industryLbl.setText("Industry: ");

        numOfStaffLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 16)); // NOI18N
        numOfStaffLbl.setForeground(new java.awt.Color(255, 255, 255));
        numOfStaffLbl.setText("Number of Staff:");

        shortGoalsLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 16)); // NOI18N
        shortGoalsLbl.setForeground(new java.awt.Color(255, 255, 255));
        shortGoalsLbl.setText("Short Term Goals:");

        longGoalsLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 16)); // NOI18N
        longGoalsLbl.setForeground(new java.awt.Color(255, 255, 255));
        longGoalsLbl.setText("Long Term Goals:");

        businessNameTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        industryTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        numOfStaffTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        shortGoalsTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        shortGoalsTf.addActionListener(this::shortGoalsTfActionPerformed);

        longGoalsTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        longGoalsTf.addActionListener(this::longGoalsTfActionPerformed);

        submitBtn.setBackground(new java.awt.Color(243, 225, 210));
        submitBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(this::submitBtnActionPerformed);

        mainBtn.setBackground(new java.awt.Color(243, 225, 210));
        mainBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 3, 16)); // NOI18N
        mainBtn.setText("Main Page");
        mainBtn.addActionListener(this::mainBtnActionPerformed);

        voteBtn.setBackground(new java.awt.Color(243, 225, 210));
        voteBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 3, 16)); // NOI18N
        voteBtn.setText("Vote App");
        voteBtn.addActionListener(this::voteBtnActionPerformed);

        reportBtn.setBackground(new java.awt.Color(243, 225, 210));
        reportBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 3, 16)); // NOI18N
        reportBtn.setText("Report App");
        reportBtn.addActionListener(this::reportBtnActionPerformed);

        soletraderRB.setBackground(new java.awt.Color(243, 225, 210));
        radiobutton.add(soletraderRB);
        soletraderRB.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 16)); // NOI18N
        soletraderRB.setText("Sole Trader");
        soletraderRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        soletraderRB.addActionListener(this::soletraderRBActionPerformed);

        partnershipRB.setBackground(new java.awt.Color(243, 225, 210));
        radiobutton.add(partnershipRB);
        partnershipRB.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 16)); // NOI18N
        partnershipRB.setText("Partnership");
        partnershipRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        partnershipRB.addActionListener(this::partnershipRBActionPerformed);

        limitedRB.setBackground(new java.awt.Color(243, 225, 210));
        radiobutton.add(limitedRB);
        limitedRB.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 16)); // NOI18N
        limitedRB.setText("LLC");
        limitedRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        limitedRB.addActionListener(this::limitedRBActionPerformed);

        displayBtn.setBackground(new java.awt.Color(243, 225, 210));
        displayBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 18)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(this::displayBtnActionPerformed);

        searchBtn.setBackground(new java.awt.Color(243, 225, 210));
        searchBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 3, 18)); // NOI18N
        searchBtn.setText("Search by Type");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        deleteBtn.setBackground(new java.awt.Color(243, 225, 210));
        deleteBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 18)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        ownerLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 16)); // NOI18N
        ownerLbl.setForeground(new java.awt.Color(255, 255, 255));
        ownerLbl.setText("Owner:");

        ownerTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ownerTf.addActionListener(this::ownerTfActionPerformed);

        owner1Lbl.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 16)); // NOI18N
        owner1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        owner1Lbl.setText("Owner 1:");

        owner2Lbl.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 16)); // NOI18N
        owner2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        owner2Lbl.setText("Owner 2:");

        owner1Tf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        owner2Tf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ceoLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 16)); // NOI18N
        ceoLbl.setForeground(new java.awt.Color(255, 255, 255));
        ceoLbl.setText("CEO:");

        ceoTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        numOfBoardMembersLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 16)); // NOI18N
        numOfBoardMembersLbl.setForeground(new java.awt.Color(255, 255, 255));
        numOfBoardMembersLbl.setText("Number of Board Members:");

        numOfBoardMembersTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        saveBtn.setBackground(new java.awt.Color(243, 225, 210));
        saveBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 18)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        readBtn.setBackground(new java.awt.Color(243, 225, 210));
        readBtn.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 18)); // NOI18N
        readBtn.setText("View Saved");
        readBtn.addActionListener(this::readBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(businessNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(industryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numOfStaffLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(businessTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(businessNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(industryTf)
                                            .addComponent(numOfStaffTf)
                                            .addComponent(limitedRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(partnershipRB, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(soletraderRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(readBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numOfBoardMembersLbl)
                                            .addComponent(longGoalsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mainBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(reportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numOfBoardMembersTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(voteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(owner2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ownerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(owner1Lbl)
                                                        .addComponent(owner2Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(ceoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(ownerTf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(ceoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(24, 24, 24)
                                                            .addComponent(owner1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(longGoalsLbl)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shortGoalsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shortGoalsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(infoLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLbl2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(businessNameLbl)
                            .addComponent(businessNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(industryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(industryTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOfStaffLbl)
                            .addComponent(numOfStaffTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(businessTypeLbl)
                            .addComponent(soletraderRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(partnershipRB)
                            .addComponent(ceoLbl)
                            .addComponent(ceoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limitedRB)
                            .addComponent(numOfBoardMembersTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfBoardMembersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shortGoalsLbl)
                            .addComponent(longGoalsLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ownerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(owner1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(owner1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(owner2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(owner2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shortGoalsTf)
                    .addComponent(longGoalsTf, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(readBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shortGoalsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortGoalsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shortGoalsTfActionPerformed

    private void longGoalsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longGoalsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longGoalsTfActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        //this is to make sure that a radio button is selected before you submit
        //could put in the else statement and will not need this code here, will test tomorrow
        /*if(!soletraderRB.isSelected()&&!partnershipRB.isSelected()&&!limitedRB.isSelected()){
            JOptionPane.showMessageDialog(null,"You must select a business type to submit!");
        }OPTED FOR ELSE STATEMENT AT THE END DO REDUCE CODE*/
        if (soletraderRB.isSelected()) {
            String owner = ownerTf.getText();
            //added this afterwards to help search by type           
            String businessType = "Sole Trader";
            String businessName = businessNameTf.getText();
            String industry = industryTf.getText();
            //if user enters text for num of staff it crashes the app, will try use try,catch method
            String shortTermGoals = shortGoalsTf.getText();
            String longTermGoals = longGoalsTf.getText();
            //try/catch -- works will implement in other radio button sections
            int numOfStaff;
            try {
                numOfStaff = Integer.parseInt(numOfStaffTf.getText());
            } catch (NumberFormatException error) {
                JOptionPane.showMessageDialog(null, "You have to enter a whole number for the number of staff field");
                return;
            }
            //this is an if statement to check if user has inputed all fields
            if (owner.equals("") || businessName.equals("") || industry.equals("") || shortTermGoals.equals("") || longTermGoals.equals("") || numOfStaffTf.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "You must fill out all fields if you want us to seriously consider aassisting you!");
                //works but still adds object to array will need to put an else statement possibly | UPDATE: it works, will implement in all radio buttins
            } else {
                //adds object to array list
                SoleTrader st = new SoleTrader(owner, businessType, businessName, industry, numOfStaff, shortTermGoals, longTermGoals);
                businessList.add(st);
                //clear text fields so you know you have submitted afterwards
                ownerTf.setText("");
                businessNameTf.setText("");
                industryTf.setText("");
                numOfStaffTf.setText("");
                shortGoalsTf.setText("");
                longGoalsTf.setText("");
                //to uncheck radio button group
                radiobutton.clearSelection();
            }
        } else if (partnershipRB.isSelected()) {
            String owner1 = owner1Tf.getText();
            String owner2 = owner2Tf.getText();
            //added this afterwards to help search by type
            String businessType = "Partnership";
            String businessName = businessNameTf.getText();
            String industry = industryTf.getText();

            String shortTermGoals = shortGoalsTf.getText();
            String longTermGoals = longGoalsTf.getText();
            //try/catch -- works will implement in other radio button sections
            int numOfStaff;
            try {
                numOfStaff = Integer.parseInt(numOfStaffTf.getText());
            } catch (NumberFormatException error) {
                JOptionPane.showMessageDialog(null, "You have to enter a whole number for the number of staff field");
                return;
            }
            //this is an if statement to check if user has inputed all fields
            if (owner1.equals("") || owner2.equals("") || businessName.equals("") || industry.equals("") || shortTermGoals.equals("") || longTermGoals.equals("") || numOfStaffTf.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "You must fill out all fields if you want us to seriously consider aassisting you!");
                //works but still adds object to array will need to put an else statement possibly | UPDATE: it works, will implement in all radio buttins
            } else {
                //adds object to array list           
                Partnership p = new Partnership(owner1, owner2, businessType, businessName, industry, numOfStaff, shortTermGoals, longTermGoals);
                businessList.add(p);
                //clear text fields so you know you have submitted afterwards
                owner1Tf.setText("");
                owner2Tf.setText("");
                businessNameTf.setText("");
                industryTf.setText("");
                numOfStaffTf.setText("");
                shortGoalsTf.setText("");
                longGoalsTf.setText("");
                //to uncheck radio button group
                radiobutton.clearSelection();
            }
        } else if (limitedRB.isSelected()) {
            String ceo = ceoTf.getText();
            //added this afterwards to help search by type
            String businessType = "LLC";
            String businessName = businessNameTf.getText();
            String industry = industryTf.getText();

            String shortTermGoals = shortGoalsTf.getText();
            String longTermGoals = longGoalsTf.getText();
            //will have to use same try catch for num of board members 
            //try/catch -- works will implement in other radio button sections
            int numOfStaff;
            try {
                numOfStaff = Integer.parseInt(numOfStaffTf.getText());
            } catch (NumberFormatException error) {
                JOptionPane.showMessageDialog(null, "You have to enter a whole number for the number of staff field");
                return;
            }
            //try/catch -- works will implement in other radio button sections
            int numOfBoardMembers;
            try {
                numOfBoardMembers = Integer.parseInt(numOfBoardMembersTf.getText());
            } catch (NumberFormatException error) {
                JOptionPane.showMessageDialog(null, "You have to enter a whole number for the number of board members field");
                return;
            }
            //this is an if statement to check if user has inputed all fields
            if (ceo.equals("") || numOfBoardMembersTf.getText().equals("") || businessName.equals("") || industry.equals("") || shortTermGoals.equals("") || longTermGoals.equals("") || numOfStaffTf.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "You must fill out all fields if you want us to seriously consider aassisting you!");
                //works but still adds object to array will need to put an else statement possibly | UPDATE: it works, will implement in all radio buttins
            } else {
                //adds object to array list           
                LLC llc = new LLC(ceo, businessType, businessName, industry, numOfStaff, shortTermGoals, longTermGoals, numOfBoardMembers);
                businessList.add(llc);
                //clear text fields so you know you have submitted afterwards
                ceoTf.setText("");
                numOfBoardMembersTf.setText("");
                businessNameTf.setText("");
                industryTf.setText("");
                numOfStaffTf.setText("");
                shortGoalsTf.setText("");
                longGoalsTf.setText("");
                //to uncheck radio button group
                radiobutton.clearSelection();
            }
        } //maybe else statement here incase no rb is selected?
        else {
            JOptionPane.showMessageDialog(null, "You must select a business type to submit an application!");
        }
        //this is to remove all labels and text fields after submission so once a radio button is selected they will appear again
        ownerLbl.setVisible(false);
        ownerTf.setVisible(false);
        owner1Lbl.setVisible(false);
        owner1Tf.setVisible(false);
        owner2Lbl.setVisible(false);
        owner2Tf.setVisible(false);
        ceoLbl.setVisible(false);
        ceoTf.setVisible(false);
        numOfBoardMembersLbl.setVisible(false);
        numOfBoardMembersTf.setVisible(false);
    }//GEN-LAST:event_submitBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        //linkning the main page through the main button
        new AfterLoginUI(l).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        new ReportUI(l).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reportBtnActionPerformed

    private void voteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteBtnActionPerformed
        // TODO add your handling code here:
        new VoteGUI(l).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_voteBtnActionPerformed

    private void soletraderRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soletraderRBActionPerformed
        // TODO add your handling code here:
        //to make different fields appear and dsiappear depending on what rb is selected
        ownerLbl.setVisible(true);
        ownerTf.setVisible(true);
        owner1Lbl.setVisible(false);
        owner1Tf.setVisible(false);
        owner2Lbl.setVisible(false);
        owner2Tf.setVisible(false);
        ceoLbl.setVisible(false);
        ceoTf.setVisible(false);
        numOfBoardMembersLbl.setVisible(false);
        numOfBoardMembersTf.setVisible(false);
    }//GEN-LAST:event_soletraderRBActionPerformed

    private void ownerTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerTfActionPerformed

    private void partnershipRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partnershipRBActionPerformed
        // TODO add your handling code here:
        //to make different fields appear and dsiappear depending on what rb is selected
        ownerLbl.setVisible(false);
        ownerTf.setVisible(false);
        owner1Lbl.setVisible(true);
        owner1Tf.setVisible(true);
        owner2Lbl.setVisible(true);
        owner2Tf.setVisible(true);
        ceoLbl.setVisible(false);
        ceoTf.setVisible(false);
        numOfBoardMembersLbl.setVisible(false);
        numOfBoardMembersTf.setVisible(false);
    }//GEN-LAST:event_partnershipRBActionPerformed

    private void limitedRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitedRBActionPerformed
        // TODO add your handling code here:
        //to make different fields appear and dsiappear depending on what rb is selected
        ownerLbl.setVisible(false);
        ownerTf.setVisible(false);
        owner1Lbl.setVisible(false);
        owner1Tf.setVisible(false);
        owner2Lbl.setVisible(false);
        owner2Tf.setVisible(false);
        ceoLbl.setVisible(true);
        ceoTf.setVisible(true);
        numOfBoardMembersLbl.setVisible(true);
        numOfBoardMembersTf.setVisible(true);
    }//GEN-LAST:event_limitedRBActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        //if statement to let you know that if there is no objects in array it cannot display
        if (businessList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no applications to display!");
        }
        //had to use abstract class for business template so i could use getdetails method for each seperate business type other wise i was not able to get individual variables for example owner. ceo etc
        for (int i = 0; i < businessList.size(); i++) {
            displayMessage
                    = businessList.get(i).getDetails()
                    + "\nBusiness Type: " + businessList.get(i).getBusinessType()
                    + "\nBusiness Name: " + businessList.get(i).getBusinessName()
                    + "\nIndustry: " + businessList.get(i).getIndustry()
                    + "\nNumber of staff: " + businessList.get(i).getNumOfStaff()
                    + "\nShort Term Goals: " + businessList.get(i).getShortTermGoals()
                    + "\nLong Term Goals: " + businessList.get(i).getLongTermGoals();

            //JOPtion pane wont work with listing all variables since different classes have different variables
            /*JOptionPane.showMessageDialog(null, "Owner: " + businessList.get(i).getOwner() + "\n Business Name: " + businessList.get(i).getBusinessName() + "\n Industry: " + businessList.get(i).getIndustry() + "\n Number of Staff: " + businessList.get(i).getNumOfStaff() + "\n Short Term Goals: " + businessList.get(i).getShortTermGoals() + "\n Long Term Goals: " + businessList.get(i).getLongTermGoals());*/
            JOptionPane.showMessageDialog(null, displayMessage);
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchType = JOptionPane.showInputDialog(null, "Please enter the type you wish to search for:");
        for (int i = 0; i < businessList.size(); i++) {
            if (searchType.equalsIgnoreCase(businessList.get(i).getBusinessType())) {
                JOptionPane.showMessageDialog(null, businessList.get(i).getDetails()
                        + "\nBusiness Type: " + businessList.get(i).getBusinessType()
                        + "\nBusiness Name: " + businessList.get(i).getBusinessName()
                        + "\nIndustry: " + businessList.get(i).getIndustry()
                        + "\nNumber of staff: " + businessList.get(i).getNumOfStaff()
                        + "\nShort Term Goals: " + businessList.get(i).getShortTermGoals()
                        + "\nLong Term Goals: " + businessList.get(i).getLongTermGoals());
            } else if (!searchType.equalsIgnoreCase(businessList.get(i).getBusinessType())) {
                JOptionPane.showMessageDialog(null, "There are no entries matching your search!");
            }
        }
        if (businessList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There has been no submissions yet!");
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        //will only use the name, industry and number of staff to delete entries to make the code more simple
        if (businessNameTf.getText().equals("") || industryTf.getText().equals("") || numOfStaffTf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You have to fill out the business name, industry and number of staff to delete its submission.");
        } else if (businessList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no entries to delete at this moment of time.");
        } else {
            String businessName = businessNameTf.getText();
            String industry = industryTf.getText();
            int numOfStaff = Integer.parseInt(numOfStaffTf.getText());

            for (int i = 0; i < businessList.size(); i++) {
                if (businessList.get(i).getBusinessName().equals(businessName) && businessList.get(i).getIndustry().equals(industry) && businessList.get(i).getNumOfStaff() == numOfStaff) {
                    businessList.remove(i);
                    JOptionPane.showMessageDialog(null, "Deleted item at index " + i);
                    break;
                }
                if (i == businessList.size() - 1) {
                    JOptionPane.showMessageDialog(null, "The item you were trying to delete could not be found.");
                }
            }
        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(businessList);
            
            JOptionPane.showMessageDialog(null,"File has been saved successfully!");
            oStream.close(); 
            
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error writing to file: " + e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        // TODO add your handling code here:
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList <Business> bList;
            bList = (ArrayList<Business>) oStream.readObject();
            for(Business b: bList){
                JOptionPane.showMessageDialog(null, b.getDetails() +
                        "\nBusiness Type: " + b.getBusinessType() + 
                        "\nBusiness Name: " + b.getBusinessName() +
                        "\nIndustry: " + b.getIndustry() +
                        "\nNumber of Staff: " + b.getNumOfStaff() +
                        "\nShort Term Goals: " + b.getShortTermGoals() + 
                        "\nLong Term Goals: " + b.getLongTermGoals()
                );
            }
            oStream.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error reading file:" + e);
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }//GEN-LAST:event_readBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContactMentorGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel businessNameLbl;
    private javax.swing.JTextField businessNameTf;
    private javax.swing.JLabel businessTypeLbl;
    private javax.swing.JLabel ceoLbl;
    private javax.swing.JTextField ceoTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel industryLbl;
    private javax.swing.JTextField industryTf;
    private javax.swing.JLabel infoLbl1;
    private javax.swing.JLabel infoLbl2;
    private javax.swing.JRadioButton limitedRB;
    private javax.swing.JLabel longGoalsLbl;
    private javax.swing.JTextField longGoalsTf;
    private javax.swing.JButton mainBtn;
    private javax.swing.JLabel numOfBoardMembersLbl;
    private javax.swing.JTextField numOfBoardMembersTf;
    private javax.swing.JLabel numOfStaffLbl;
    private javax.swing.JTextField numOfStaffTf;
    private javax.swing.JLabel owner1Lbl;
    private javax.swing.JTextField owner1Tf;
    private javax.swing.JLabel owner2Lbl;
    private javax.swing.JTextField owner2Tf;
    private javax.swing.JLabel ownerLbl;
    private javax.swing.JTextField ownerTf;
    private javax.swing.JRadioButton partnershipRB;
    private javax.swing.ButtonGroup radiobutton;
    private javax.swing.JButton readBtn;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel shortGoalsLbl;
    private javax.swing.JTextField shortGoalsTf;
    private javax.swing.JRadioButton soletraderRB;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton voteBtn;
    // End of variables declaration//GEN-END:variables
}
